### ISSUE TITLE
Will PouchDB be added to the chart?

### ISSUE THREAD

**Issue by bhajneet** [mrousavy/StorageBenchmark#5]
Just a quick question, wondering if there are any plans to add other storage items/options to the graph.

**Comment by SC-One** [comment]
And FasterKV
https://github.com/microsoft/FASTER

**Comment by mrousavy** [comment]
> And FasterKV

Huh? That lib is in C#, StorageBenchmark is for React Native

**Comment by mrousavy** [comment]
> Will PouchDB be added to the chart?

@bhajneet sure - if you want to add it, submit a PR here and I'll review / compare perf :)

**Comment by SC-One** [comment]
> > And FasterKV
> 
> Huh? That lib is in C#, StorageBenchmark is for React Native

I know , but it's not bad to have comparing theme too.(I know it's not equivalent comparing , but it's not bad idea)
Thanks.

**Comment by mrousavy** [comment]
I don't think you understand - StorageBenchmark is a React Native app that compares performances of React Native Storage libraries. **FasterKV is not a React Native storage library**.
